aws_region              = "us-east-1"
bucket_name             = "myterrfstate"
github_org              = "yusuf2211"
github_actions_oidc_url = "https://token.actions.githubusercontent.com"
github_repo             = "rsschool-devops-course-tasks"
